app:
  port: 8887

db:
  host: "localhost"
  port: 3306
  database: "blog"
  username: "root"
  password: "12345."

log:
  level: "info" # debug, info, warn, error
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backups: 5
  max_age: 30 # days
  compress: true # 是否压缩旧日志文件
  format: "text" # json, text
  show_caller: false # 是否显示调用者信息
  console: true # 是否同时输出到控制台